### ISSUE TITLE
Bevry not showing up as a project requiring funding

### ISSUE THREAD

**Issue by balupton** [opencollective/backyourstack#55]
So I just logged in via github, and granted access to @bevry and @docpad

However, https://backyourstack.com/docpad doesn't list https://backyourstack.com/bevry even though https://backyourstack.com/docpad/dependencies lists many https://backyourstack.com/bevry/repositories such as http://npmjs.com/package/ambi

Is this a caching issue? If so, here are the screenshots:

![screen shot 2018-08-10 at 7 35 12 am](https://user-images.githubusercontent.com/61148/43931312-6f9df52e-9c70-11e8-87e3-7854d2ebc896.png)

![screen shot 2018-08-10 at 7 35 21 am](https://user-images.githubusercontent.com/61148/43931315-71c0c2c8-9c70-11e8-9b4a-dbd8e47ba01d.png)

**Comment by znarf** [comment]
Looks like the issue is that we don't match Bevry (and its packages) as a project requiring funding.

To inspect how we do the matching, everything is in this file: https://github.com/opencollective/backyourstack/blob/master/src/data/projects.json

We computed most of this list programatically, it's not perfect.

I just checked, you are on Open Collective, https://opencollective.com/bevry, it might be that you don't have a githubRepo or githubAccount in your settings. This is something that is usually filled on sign up.

I'm looking at it and will keep you updated.

**Comment by znarf** [comment]
Fixed in: https://github.com/opencollective/backyourstack/commit/68505e0b2e6a0ddd91595aa1c20ac3ee65f4e6e7

Does the list of packages looks correct?

If you check https://backyourstack.com/docpad, it's now properly detected.

**Comment by balupton** [comment]
Thanks. Looks good. What was the issue?

**Comment by znarf** [comment]
I basically explained the issue there:
https://github.com/opencollective/backyourstack/issues/55#issuecomment-412016546

I then took action and added (on Open Collective side) your GitHub organzation in your settings.

I then re-processed and updated the projects data file (that we're using to do the matching):
https://github.com/opencollective/backyourstack/commit/68505e0b2e6a0ddd91595aa1c20ac3ee65f4e6e7

**Comment by balupton** [comment]
Ok great thanks
