### ISSUE TITLE
More clarity on what is supported and not

### ISSUE THREAD

**Issue by znarf** [opencollective/backyourstack#57]
We got multiple times that kind of feedback: https://twitter.com/freakboy3742/status/1027477767720300544

Let's try to integrate that.

**Comment by piamancini** [comment]
This might help for now https://github.com/opencollective/backyourstack/pull/58

**Comment by znarf** [comment]
@piamancini the complain is that it's not upfront enough. they would like to see something on the homepage, and some warning in the results page.

**Comment by piamancini** [comment]
Totally, but I also received a couple of, it should be in the readme, so at least let's get this done now

**Comment by znarf** [comment]
Great, merged #58.

**Comment by welkie** [comment]
I think what would improve this whole situation is if the projects could describe in a consistent manner what their support model is. For example, a `package.json` could have a `support` property whose value is a URL to whichever web page is associated with how they get their funding. Any tool developed by the community, like BackYourStack, could read this and know how to present the information. The URL could be pattern matched for sites like OpenCollective and Patreon, so that tools could tailor how they display the information if they recognise the site in the URL. At the end of the day, even support URLs that just lead to a person's personal website would be represented. They would be too custom to display well on platforms like BackYourStack, but they would be represented nonetheless.

I wonder how much effort it would be to get that kind of change propagated throughout the programming ecosystem.

**Comment by znarf** [comment]
https://github.com/opencollective/backyourstack/pull/83
